name: v*.*.* -PR-> master

on:
  push:
    branches: [ v*.*.* ]

jobs:
  auto-pr:
    name: Automated Master Branch PR
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
          - name: Extract branch name on pull request
            shell: bash
            run: |
              echo "DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
              echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          - name: Print debug data before publishing
            run: |
              echo "Source branch: ${{ env.SOURCE_BRANCH }}"
              echo "   Event name: ${{ github.event_name }}"
              echo "  Repo. name: ${{ github.event.repository.name }}"
          # ref.: https://github.com/actions/checkout, v3.0.0
          - name: Checkout repository
            uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
          - name: Create PR from a version branch to master after version branch push
            if: startsWith(env.SOURCE_BRANCH, 'v') && contains(env.SOURCE_BRANCH, '.')
            uses: repo-sync/pull-request@5ba2c80b97c87b9174c1548141b7acd80f6376e1
            with:
              github_token: ${{ secrets.REPO_ACCESS }}
              source_branch: ${{ env.SOURCE_BRANCH }}
              destination_branch: ${{ env.DEFAULT_BRANCH }}
              pr_title: "${{ env.SOURCE_BRANCH }} -> ${{ env.DEFAULT_BRANCH }}" 
              pr_label: "kira-automation"
              pr_assignee: "asmodat"
              pr_allow_empty: true